title: Lúcio Camara e Silva
logo: <img src="https://github.com/ednaelxd/portfolio/blob/main/assets/imagem_2024-07-16_141757048.png">
discription: Portifólio pessoal de projetos
# show_downloads: True
theme: jekyll-theme-minimal
